apply plugin: 'java-library'

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

sourceSets {
    main {
        java.srcDirs = ['src/main/java']
        resources.srcDirs = []
    }
}

dependencies {
    api "com.badlogicgames.gdx:gdx:$gdxVersion"
    api "com.badlogicgames.gdx:gdx-bullet:$gdxVersion"
    api "com.github.mgsx-dev.gdx-gltf:gltf:$gdxGltfVersion"
}
